import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER


def create_pdf(cam_data: dict) -> bytes:
    """
    Module 8: Credit Appraisal Memo Generator
    Generates a professional PDF and returns raw bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm,
                            leftMargin=2.5 * cm, rightMargin=2.5 * cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], alignment=TA_CENTER,
                                 fontSize=20, spaceAfter=6, textColor=colors.HexColor("#0f172a"))
    sub_style = ParagraphStyle("Sub", parent=styles["Normal"], alignment=TA_CENTER,
                               fontSize=10, textColor=colors.HexColor("#64748b"))
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceBefore=14,
                              spaceAfter=6, textColor=colors.HexColor("#1e293b"))
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=16,
                                textColor=colors.HexColor("#334155"))

    company = cam_data.get("company", {})
    financials = cam_data.get("financials", {})
    risk = cam_data.get("risk", {})
    decision = cam_data.get("decision", {})
    research = cam_data.get("research", {})

    status = decision.get("status", "N/A")
    status_color = colors.HexColor("#10b981") if status == "Approved" else (
        colors.HexColor("#f59e0b") if status == "Conditional Approval" else colors.HexColor("#ef4444"))

    story = []

    # Header
    story.append(Paragraph("CREDIT APPRAISAL MEMO", title_style))
    story.append(Paragraph("Generated by IntelliCredit Autonomous Engine", sub_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#2563eb"), spaceAfter=16))

    # 1. Executive Summary
    story.append(Paragraph("1. Executive Summary", h2_style))
    story.append(Paragraph(
        f"The AI Credit Analyst recommends a status of <b>{status}</b> for <b>{company.get('name', 'N/A')}</b>. "
        f"The recommended credit limit is ₹{decision.get('recommended_limit', 0):,.0f} at an interest rate of "
        f"{decision.get('interest_rate', 'N/A')}. Risk category: <b>{decision.get('category', 'N/A')}</b>.",
        body_style,
    ))

    # Decision banner table
    story.append(Spacer(1, 10))
    decision_table = Table([[f"DECISION: {status}"]], colWidths=["100%"])
    decision_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), status_color),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTSIZE", (0, 0), (-1, -1), 14),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))
    story.append(decision_table)
    story.append(Spacer(1, 14))

    # 2. Company Information
    story.append(Paragraph("2. Company Information", h2_style))
    company_rows = [
        ["Field", "Value"],
        ["Company Name", company.get("name", "N/A")],
        ["Industry", company.get("industry", "N/A")],
        ["Years in Operation", str(company.get("years", "N/A"))],
        ["Annual Revenue", f"₹{company.get('revenue', 0):,.0f}"],
        ["Loan Requested", f"₹{company.get('requested', 0):,.0f}"],
        ["Existing Liabilities", f"₹{company.get('liabilities', 0):,.0f}"],
    ]
    _add_table(story, company_rows)

    # 3. Financial Ratios
    story.append(Paragraph("3. Financial & Risk Overview", h2_style))
    fin_rows = [
        ["Metric", "Value"],
        ["ML Risk Score", f"{risk.get('score', 0)} / 100"],
        ["Probability of Default", f"{risk.get('pd_percentage', 0)}%"],
        ["Profit Margin", f"{financials.get('profit_margin', 0)}%"],
        ["Debt-to-Equity Ratio", str(financials.get('debt_to_equity', 0))],
        ["Current Ratio", str(financials.get('current_ratio', 0))],
        ["Interest Coverage", f"{financials.get('interest_coverage', 0)}x"],
        ["Revenue Growth (YoY)", f"{financials.get('revenue_growth', 0)}%"],
        ["Web Sentiment Score", f"{research.get('web_sentiment', 0)} / 100"],
        ["Industry Outlook", research.get("industry_outlook", "N/A")],
        ["Legal Disputes", str(research.get("legal_disputes", 0))],
    ]
    _add_table(story, fin_rows)

    # 4. AI Reasoning
    story.append(Paragraph("4. AI Reasoning (Explainable AI)", h2_style))
    for reason in decision.get("explanation", []):
        story.append(Paragraph(f"• {reason}", body_style))
    story.append(Spacer(1, 6))

    # 5. Recommended Lending Terms
    story.append(Paragraph("5. Recommended Lending Terms", h2_style))
    terms_rows = [
        ["Parameter", "Value"],
        ["Recommended Credit Limit", f"₹{decision.get('recommended_limit', 0):,.0f}"],
        ["Interest Rate", decision.get("interest_rate", "N/A")],
        ["Risk Category", decision.get("category", "N/A")],
    ]
    _add_table(story, terms_rows)

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "This document was autonomously generated by IntelliCredit AI Engine. "
        "It is intended for internal use only and must be reviewed by a certified credit officer.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8,
                       textColor=colors.HexColor("#94a3b8"), alignment=TA_CENTER),
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def _add_table(story, rows):
    """Helper: renders a styled data table."""
    t = Table(rows, colWidths=[8 * cm, 9 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8fafc"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(t)
    story.append(Spacer(1, 10))
